#/* < DTS2014042900710 shenjinming 20140430 begin */
# Makefile for the DSM drivers.
#
# Each configuration option enables a list of files.
#/* < DTS2014121803938 yangzhonghua 20141218 begin */
obj-$(CONFIG_HUAWEI_DSM)  += dsm_core.o dsm_keys.o
#/* DTS2014121803938 yangzhonghua 20141218 end > */

#/* DTS2014042900710 shenjinming 20140430 end > */