obj-$(CONFIG_SENSORS)		+= sensors_class.o
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
#/* < DTS2014041705903 zhangmin 20140418 begin */
obj-y += sensor_info.o
#/* DTS2014041705903 zhangmin 20140418 end > */