#/* < DTS2014021207582 xufeng 20140212 begin */
obj-$(CONFIG_HUAWEI_KSTATE)          += hw_kstate.o
#/* DTS2014021207582 xufeng 20140212 end > */

obj-$(CONFIG_HUAWEI_KSTATE)          += hw_packetmonitor.o
obj-$(CONFIG_HUAWEI_KSTATE)          += hw_kcollect.o
