#/* < DTS2014060603241 chenjikun 20140610 add >*/
obj-$(CONFIG_HUAWEI_LOG_MODULE) += log_module.o
obj-$(CONFIG_HUAWEI_LOG_MODULE) += log_module_debug_mask_example.o
obj-$(CONFIG_HUAWEI_LOG_MODULE) += log_module_dynamic_debug_example.o
