# Makefile for the equip drivers.
#

# Each configuration option enables a list of files.
#/*Begin <DTS2012120510674>  add by nielimin/00164272 for normalizing internal interface of AT command  2012/12/5*/
obj-$(CONFIG_DEV_EQUIP) += equip.o
#BEGIN:DTS2013093006188 added by huyouhua 00136760 at 20130930 for Flash MMI Test
obj-y += equip.o
#END:DTS2013093006188 added by huyouhua 00136760 at 20130930 for Flash MMI Test
#/*End <DTS2012120510674>  add by nielimin/00164272 for normalizing internal interface of AT command  2012/12/5*/
