#/* < DTS2013123108349 caowei 20140104 begin */
#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
#focaltech_ex_fun.o
#/* < DTS2014021201959 caowei 20140213 begin */
obj-$(CONFIG_MSG2138_GC) += msg2138_qc.o
obj-$(CONFIG_MSG2138_SCAP_TEST) += msg2138_scap_test.o 
#/* DTS2014021201959 caowei 20140213 end >*/
#/* DTS2013123108349 caowei 20140104 end >*/